### ISSUE TITLE
0.3.1 segy_writer bug

### ISSUE THREAD

**Issue by lvdai15621** [trhallam/segysak#102]
error out:   'FrozenDict' object does not support item assignment
0.3.0 with no similar error.

**Comment by trhallam** [comment]
Can you provide more details about how you are generating this error please?

What arguments are you passing to the function? What is the full stack trace of the error? Do you have a minimum reproducible example that generates the error (https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by lvdai15621** [comment]
I import segy_writer at the beginning:  "from segysak.segy import segy_writer"

error occurs at the code : "segy_writer(self.seisnc, export_path, trace_header_map=self.trace_header_map)" ( I have established a class based on segysak)

"trace_header_map" is descibed as:
       
 self.trace_header_map = {
            'iline': self.head_dict['iline'],
            'xline': self.head_dict['xline'],
            'cdp_x': self.head_dict['cdpx'],
            'cdp_y': self.head_dict['cdpy']
        }

all of the above is good in 0.3.0, but not ok in 0.3.1

Thanks for the reply.

**Comment by trhallam** [comment]
Ok, I think this got identified and fixed after the release but I didn't get around to publishing it. Can you please update to 0.3.2 and try again?

**Comment by trhallam** [comment]
Closing, no feedback from user.
