### ISSUE TITLE
Example: General manipulations using xarray.

### ISSUE THREAD

**Issue by trhallam** [trhallam/segysak#11]
- [x] Create an example where the seismic cube/2d/gathers are cropped by sub-selection.
- [ ] Collapse gathers to a stack using xarray.sum
- [ ] Rename dimensions using xarray.rename_dims
- [x] Examples of selecting over dimensions and dimension ranges using .sel and .isel
- [ ] Filtering data using xarray.where
- [x] Apply numpy functions to a dataset
- [ ] How to apply filters to an xarray efficiently using ndimage
- [x] How to apply a function along a trace, like an adaptive gain filter.

Add some more guys!

**Comment by stevejpurves** [comment]
@trhallam where you thinking all this in one notebook?

**Comment by trhallam** [comment]
Fabio has kind of started this, but probably needs help and guidance.
