### ISSUE TITLE
Documentation fro header re-map trace headers

### ISSUE THREAD

**Issue by pasha9999** [trhallam/segysak#112]
Hello!

I am trying to read a SEG-Y file with non-standard header positions for the CDP coordinates (cdp_x 4-byte integer at byte 201, for example). I found that I can set it up using [segysak.segy.well_known_byte_locs](https://segysak.readthedocs.io/en/latest/generated/segysak.segy.well_known_byte_locs.html) but did not find any examples for format description. Can you, please, provide one - or link to docs, where I can find it.

Thanks,
Pavel

**Comment by trhallam** [comment]
There is an example here specifying the byte positions to the loader https://segysak.readthedocs.io/en/latest/examples/QuickOverview.html#Load-SEG-Y-data.

The API also lists the keyword arguments for `sey_loader` https://segysak.readthedocs.io/en/latest/generated/segysak.segy.segy_loader.html#segysak.segy.segy_loader

In general, any `kwarg` with a byte position can be passed and it will be loaded as a variable into the output xarray with name `kwarg`. The coordinate variables are special however as they help determine the geometry of the volume/line.

**Comment by pasha9999** [comment]
Thank you very much!

  
>Понедельник, 3 октября 2022, 16:46 +08:00 от Tony Hallam ***@***.***>:
> 
> 
>There is an example here specifying the byte positions to the loader  https://segysak.readthedocs.io/en/latest/examples/QuickOverview.html#Load-SEG-Y-data .
>The API also lists the keyword arguments for sey_loader  https://segysak.readthedocs.io/en/latest/generated/segysak.segy.segy_loader.html#segysak.segy.segy_loader
>In general, any kwarg with a byte position can be passed and it will be loaded as a variable into the output xarray with name kwarg. The coordinate variables are special however as they help determine the geometry of the volume/line.
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <trhallam/segysak/issues/112/1265124894 @ github . com> 
 
 
--
pavel shashkin
Отправлено из Почты  Mail.ru
