### ISSUE TITLE
suppress tqdm warning

### ISSUE THREAD

**Issue by aadm** [trhallam/segysak#113]
When using segysak within jupyter-lab there is an annoying warning on import issued from tdqm:

```
C:\Users\ag19324\Miniconda3\envs\work\lib\site-packages\segysak\segy\_segy_core.py:7: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm
```
By modifiying line 7 in `segysak/segy/_segy_core.py` from

```
from tqdm.autonotebook import tqdm
```

to one of these two alternatives:

(A)
```
from tqdm import tqdm_notebook as tqdm
```

(B)

```
from tqdm.auto import tqdm
```

the warning is suppressed.

As there are two alternatives and I have no good grasp of how tqdm works I hesitate on creating a pull request.

**Comment by trhallam** [comment]
Fixed in a47bf5b01a5332a3ac758d02a710f4e9fa9b789c, thanks for reporting an issue.
