### ISSUE TITLE
Example: Matplotlib with Xarray

### ISSUE THREAD

**Issue by trhallam** [trhallam/segysak#12]
- [x] Plot seismic iline and xline.
- [x] Plot seismic slice
- [x] Plot gathers
- [x] Plot cdpx and cdpy locations
- [x] Create a polygon box for the dataset
- [x] Create a live trace polygon box for the dataset
- [x] Plot a seismic slice in cdpx and cdpy, not in iline/xline
- [ ] Plot multiple 2d geometries on a map

Add more!

**Comment by banesullivan** [comment]
Any interest in expanding the viz example to 3D with PyVista?

**Comment by trhallam** [comment]
@banesullivan We've probably covered off a lot of the matplotlib examples but if you can provide some hints on how to do these things with Pyvista that would be great as well.

**Comment by banesullivan** [comment]
Figured I should finally get around to this

FYI: https://github.com/pyvista/pyvista-support/issues/320
