### ISSUE TITLE
Direct convert: segy to netcdf

### ISSUE THREAD

**Issue by etotten93** [trhallam/segysak#121]
Hi @trhallam , the ***.seisio.to_netcdf command is very useful for segy_loader objects already loaded; however, I have a memory issue when trying to load above a certain number of traces, "Unable to allocate 3.67 TiB for an array with shape (202, 448, 5001, 2228) and data type float32".

I am wondering if segysak has a command to directly convert the full/original segy file without needing to use segy_loader first (some of my SEGY files are > 50GB in size).

Many thanks in advance!

**Comment by trhallam** [comment]
The converter function or CLI should do what you want.

https://segysak.readthedocs.io/en/latest/generated/segysak.segy.segy_converter.html#segysak-segy-segy-converter

Note that converting to netcdf might inflate the size of your file.

**Comment by etotten93** [comment]
Brilliant - this converted quite quickly. From here, is it still popssible to header_scan &/or header_scrape as done previously on segy files to query the new netcdf file, using segy_header_scan and segy_header_scrape? Or do I need to call a new set of functions?

Many thanks!

**Comment by trhallam** [comment]
Can you please post the full stack trace you get when the error occurs?

**Comment by etotten93** [comment]
And the error (when trying to plot all traces in one iline):

    ValueError                                Traceback (most recent call last)
    <ipython-input-1-76cd4d1cfd92> in <module>
        25 #01:08 in lecture -> use trace header map for this new variable
        26 seisnc_file = './XXXXX.nc'
    ---> 27 segy_converter(segy_file, seisnc_file, iline=189, xline=193, cdpx=181,     cdpy=185,offset=None,vert_domain="TWT",\
        28 data_type="AMP",ix_crop=.   (233522,233522,716661,723677),cdp_crop=None,xy_crop=None,z_crop=None,return_geometry=False,\
        29 silent=False,extra_byte_fields=None)

    ~/anaconda3/PATH/TO/segysak/segy/_segy_loader.py in segy_converter(segyfile, ncfile, cdp, iline, xline, cdpx, cdpy,     offset, vert_domain, data_type, ix_crop, cdp_crop, xy_crop, z_crop, return_geometry, silent, extra_byte_fields, **segyio_kwargs)
      1345     indexer = indexer + ["off_index"] if offset is not None else indexer
      1346
    -> 1347     ds = _loader_converter_write_headers(
      1348         ds, head_df, indexer, dims, extra_byte_fields, is3d2d=is3d2d
      1349     )

    ~/anaconda3/lib/python3.9/site-packages/segysak/segy/_segy_loader.py in _loader_converter_write_headers(ds, head_df,     indexer, dims, extra_byte_fields, is3d2d)
       889     # we have some some geometry to assign headers to
       890     if is3d2d:
    --> 891         head_ds = head_df.set_index(indexer).to_xarray()
       892         for key, field in extra_byte_fields.items():
       893             ds[key] = (dims, head_ds[field].values)

    ~/anaconda3/PATH/TO/pandas/core/generic.py in to_xarray(self)
      3107             return xarray.DataArray.from_series(self)
      3108         else:
    -> 3109             return xarray.Dataset.from_dataframe(self)
      3110
      3111     @final

    ~/anaconda3/lPATH/TO/xarray/core/dataset.py in from_dataframe(cls, dataframe, sparse)
      5508
      5509         if isinstance(idx, pd.MultiIndex) and not idx.is_unique:
    -> 5510             raise ValueError(
      5511                 "cannot convert a DataFrame with a non-unique MultiIndex into xarray"
      5512             )

    ValueError: cannot convert a DataFrame with a non-unique MultiIndex into xarray

**Comment by trhallam** [comment]
Are you trying to overwrite an existing file?

**Comment by etotten93** [comment]
> Are you trying to overwrite an existing file?

I have removed any .nc files in the run directory to check this and still get the TypeError: Simple selection can't process 0.0'

**Comment by trhallam** [comment]
If you remove the cropping information and set the `return_geometry=True` flag do you get the same error?

**Comment by etotten93** [comment]
Sorry for the delay - on a train. Setting ix_crop = None and return_geometry=True yields:

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 162k/162k [00:06<00:00, 23.9k traces/s]
header_loaded
is_3d
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-8306e15c9b17> in <module>
     25 #01:08 in lecture -> use trace header map for this new variable
     26 seisnc_file = './nav_merge_050A069_1.nc'
---> 27 segy_converter(segy_file, seisnc_file, iline=189, xline=193, cdpx=181, cdpy=185,offset=37,vert_domain="TWT",\
     28 data_type="AMP",ix_crop=None,cdp_crop=None,xy_crop=None,z_crop=None,return_geometry=True,\
     29 silent=False,extra_byte_fields=None)

~/anaconda3/lib/python3.9/site-packages/segysak/segy/_segy_loader.py in segy_converter(segyfile, ncfile, cdp, iline, xline, cdpx, cdpy, offset, vert_domain, data_type, ix_crop, cdp_crop, xy_crop, z_crop, return_geometry, silent, extra_byte_fields, **segyio_kwargs)
   1354     with h5netcdf.File(ncfile, "a") as seisnc:
   1355         for var, darray in new_vars.items():
-> 1356             seisnc_var = seisnc.create_variable(var, darray.dims, darray.dtype)
   1357             seisnc_var[...] = darray[...]
   1358             seisnc.flush()

~/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py in create_variable(self, name, dimensions, dtype, data, fillvalue, chunks, chunking_heuristic, **kwargs)
    867         for k in keys[:-1]:
    868             group = group._require_child_group(k)
--> 869         return group._create_child_variable(
    870             keys[-1],
    871             dimensions,

~/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py in _create_child_variable(self, name, dimensions, dtype, data, fillvalue, chunks, chunking_heuristic, **kwargs)
    692 
    693         # get shape from all dimensions
--> 694         shape = tuple(self._all_dimensions[d].size for d in dimensions)
    695         maxshape = tuple(self._all_dimensions[d]._maxsize for d in dimensions if d)
    696 

~/anaconda3/lib/python3.9/site-packages/h5netcdf/core.py in <genexpr>(.0)
    692 
    693         # get shape from all dimensions
--> 694         shape = tuple(self._all_dimensions[d].size for d in dimensions)
    695         maxshape = tuple(self._all_dimensions[d]._maxsize for d in dimensions if d)
    696 

~/anaconda3/lib/python3.9/collections/__init__.py in __getitem__(self, key)
    939             except KeyError:
    940                 pass
--> 941         return self.__missing__(key)            # support subclasses that define __missing__
    942 
    943     def get(self, key, default=None):

~/anaconda3/lib/python3.9/collections/__init__.py in __missing__(self, key)
    931 
    932     def __missing__(self, key):
--> 933         raise KeyError(key)
    934 
    935     def __getitem__(self, key):

KeyError: 'iline'

which appears to be a different error.

**Comment by trhallam** [comment]
Yeah, I'm not 100% on what's going on here, often it's data related. Did you say the data was publicly available? I might have some time to look at it over the next few days. 

Otherwise, I would say that the way using segysak is a bit counterintuitive. I'll try to rework your code to be more idiomatic tomorrow.

**Comment by etotten93** [comment]
Thanks for your help, I'll get in touch tomorrow about this.

**Comment by etotten93** [comment]
Having made good progress, I am wondering why segy_converter does not like being supplied with extra_byte_fields={"SourceX":73,"SourceY":77}) (or other header attributes), erroring out with the following.

In [20]: segy_converter(segy_file, seisnc_file, iline=189, xline=193, cdpx=181, cdpy=185,offset=None,vert_domain="TWT",\
    ...: data_type="AMP",ix_crop=None,cdp_crop=None,xy_crop=None,z_crop=None,return_geometry=False,\
    ...: silent=False,extra_byte_fields={"SourceX":73,"SourceY":77})
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-7d26f7de39a0> in <module>
----> 1 segy_converter(segy_file, seisnc_file, iline=189, xline=193, cdpx=181, cdpy=185,offset=None,vert_domain="TWT",\
      2 data_type="AMP",ix_crop=None,cdp_crop=None,xy_crop=None,z_crop=None,return_geometry=False,\
      3 silent=False,extra_byte_fields={"SourceX":73,"SourceY":77})

~/anaconda3/lib/python3.9/site-packages/segysak/segy/_segy_loader.py in segy_converter(segyfile, ncfile, cdp, iline, xline, cdpx, cdpy, offset, vert_domain, data_type, ix_crop, cdp_crop, xy_crop, z_crop, return_geometry, silent, extra_byte_fields, **segyio_kwargs)
   1276     check_tracefield(byte_loc)
   1277 
-> 1278     head_df, head_bin, head_loc = _loader_converter_header_handling(
   1279         segyfile,
   1280         cdp=cdp,

~/anaconda3/lib/python3.9/site-packages/segysak/segy/_segy_loader.py in _loader_converter_header_handling(segyfile, cdp, iline, xline, cdpx, cdpy, offset, vert_domain, data_type, ix_crop, cdp_crop, xy_crop, z_crop, return_geometry, silent, extra_byte_fields, head_df, optimised_load, **segyio_kwargs)
    788     if head_df is None:
    789         # Start by scraping the headers.
--> 790         head_df = segy_header_scrape(
    791             segyfile, silent=silent, bytes_filter=scrape_bytes, **segyio_kwargs
    792         )

~/anaconda3/lib/python3.9/site-packages/segysak/segy/_segy_headers.py in segy_header_scrape(segyfile, partial_scan, silent, bytes_filter, chunk, **segyio_kwargs)
     82         pandas.DataFrame: Raw header information in table for scanned traces.
     83     """
---> 84     check_tracefield(bytes_filter)
     85 
     86     assert (chunk > 0) and isinstance(chunk, int)

~/anaconda3/lib/python3.9/site-packages/segysak/segy/_segy_core.py in check_tracefield(byte_list)
     43     ]
     44     if failed:
---> 45         raise ValueError(f"Invalid byte locations: {failed}")
     46 
     47     return True

ValueError: Invalid byte locations: ['SourceX', 'SourceY']

Thanks!

**Comment by trhallam** [comment]
Please use keys that match values from `segyio.tracefield.keys`

**Comment by teoeq** [comment]
Anyone tried to convert segy to netcdf that could be used as an input in ArcGIS Pro to create voxel layer? Thanks

**Comment by trhallam** [comment]
Issue resolved by user.
