### ISSUE TITLE
Inconcistency in shapes (2D seismic) causes error when calling segy_loader

### ISSUE THREAD

**Issue by MadsLorentzen** [trhallam/segysak#123]
I am trying to load in a 2D seismic section. According to the header information (TRACE_SAMPLE_COUNT), the data holds 5359 samples. 
![image](https://github.com/trhallam/segysak/assets/50207393/a3aa1327-a8b6-4a4b-9b6e-7f6d0002bbc7)

However, when attempting to load it in segysak, I get the following error

![image](https://github.com/trhallam/segysak/assets/50207393/3761ba4f-073d-452b-9300-6161031ad3c1)

**Comment by trhallam** [comment]
Likely this means there are some issues with your headers. Probably one CDP is duplicated in this case would be my guess. Have  look at the headers to ensure each CDP number is unique.

**Comment by trhallam** [comment]
Please try the new `open_dataset` Xarray backend in v0.5. This removed the percentiles function which is no longer required due to lazy loading.
