### ISSUE TITLE
Get all tests in `tests` to pass

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#14]
The pytest tests are not all running, if we can get them updated and green then we can hook them up to a github action and keep them green on PRs

**Comment by trhallam** [comment]
The tests are currently passing https://github.com/trhallam/segysak/commit/d8c0188d6f2f88d32d0fff7736ea9375a2d8c6d9

**Comment by Gijsbertbas** [comment]
Tests run except for one... this line: https://github.com/trhallam/segysak/blob/71452c8fbd6cfdd0094510c414dda03c0ef56677/tests/test_seismic_segy.py#L156 fails to load [this file](https://github.com/trhallam/segysak/blob/t20-master/tests/test-data-segyio/text-embed-null.sgy) with error mentioned in [this section](http://docs.h5py.org/en/2.3/strings.html#variable-length-ascii) (VLEN strings to not support embedded NULLs...)

**Comment by trhallam** [comment]
These tests failed due to the addition of pretty strings in notebooks. The strings have to downgraded and upgraded on save to netcdf to avoid errors. https://github.com/trhallam/segysak/commit/003c8076699cd6845c16f6dc3f56544b513d79d0 should address this.
