### ISSUE TITLE
Convert CLI from argparse to click.

### ISSUE THREAD

**Issue by trhallam** [trhallam/segysak#15]
Subcomands:
 - [ ] ascii: ascii out of headers/ebcidc
 - [ ] scan: scan headers ebcidc
 - [ ] nc: process netcdf hdf5 input files
 - [ ] segy: process segy input files

 - [ ] Improve README docs to reflect changes.

**Comment by Gijsbertbas** [comment]
I started looking at this!

**Comment by trhallam** [comment]
Got it thanks. I probably wasn't super explicit in what we are looking for, hopefully it is kind of intuitive.

**Comment by Gijsbertbas** [comment]
as I understand it the argparse implementation should be replaces by using Click for (at least) the above subcommands
