### ISSUE TITLE
Rate of data being read/load

### ISSUE THREAD

**Issue by fabioaco** [trhallam/segysak#22]
There is a rate reported as the data is scrapped. The current rate is 'it/s' that stands for iterations per seconds.
Could this be a more meaningful rate? For instance

- trace/second

- bites/second
![image (1)](https://user-images.githubusercontent.com/21201884/83954944-f683c380-a84d-11ea-80ee-8705339eadc8.png)

**Comment by trhallam** [comment]
The default arguments/format for `tqdm` needs to be changed in `segysak.segy` to tell the user more literally what is going on.
