### ISSUE TITLE
Example: Extract data from a 3D volume using a horizon surface

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#26]
- [x] load 3D twt data
 - [x] load a horizon e.g. top hugin (into an Xarray?)
 - [x] extract data over the horizon into a 2D map
 - [x] extract data over a horizon +/-N ms into a smaller 3D cube

**Comment by stevejpurves** [comment]
So initial idea is to use the accessor pattern to do this. I'll start by getting a notebook setup and then delve into that.

**Comment by trhallam** [comment]
Merging points to a dataframe now ready for testing and discussion https://github.com/trhallam/segysak/commit/2c6b67ec4706a864d56f964e301e1e88120a094d

**Comment by trhallam** [comment]
The example has been updated with a basic workflow but need attention for detail and clarity.
