### ISSUE TITLE
Start sphinx based documentation

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#27]
Start laying out a pattern for documentation using sphinx and get something up on read the docs

 - [x] setup sphinx
 - [x] publish "something" to readthedocs
 - [x] get a link / badge in the readme

**Comment by trhallam** [comment]
I have a segysak gmail account to register the package. The same account I used for PyPi.

**Comment by trhallam** [comment]
https://segysak.readthedocs.io/en/latest/

**Comment by trhallam** [comment]
The initial bits are done, hopefully we can more than just a default info onto the page sometime this week. @stevejpurves

**Comment by trhallam** [comment]
These are now looking in much better shape, changes pushed to the `t20-master` branch can be viewed at https://segysak.readthedocs.io/en/t20-master/
