### ISSUE TITLE
Arb line coordinates

### ISSUE THREAD

**Issue by trhallam** [trhallam/segysak#28]
We need a function that creates the sampling points for an arbline from a set of coordinates.

If you have a some points A, B & C that don't follow the grid then you will not get nice divisible distances between them. The question is how should we sample the line. Divide by N and have different sampling along each segment (no), try to use average dxdy from the grid (maybe) but this will create funny sized intervals at the end of each segment. 

This function should return a list of coordinates that can be used by `seis.xysel()`

**Comment by stevejpurves** [comment]
We have some example data from volve that came out of Petrel but its a it cryptic and also has many other factors involved like CRS definition etc... whilst it would e nice to be able to extract over an shape we'll stick to simple sets of points in the CRS of the volume for now
