### ISSUE TITLE
Add isModality() functions for downstream tasks

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#32]
If modality is the correct term here but it would be easy and useful to add some functions like:

 - is_2d()
 - is_2d_gathers()
 - is_3d()
 - is_3d_gathers()

so that the logic for working that out is encapsulated in the class

**Comment by trhallam** [comment]
Added questions to accessor in `_accessor.py` and implemented tests.

https://github.com/trhallam/segysak/commit/4fd654240ac47a20b50fba339a854c9c4b740c20
