### ISSUE TITLE
Cropping via the CLI command breaks

### ISSUE THREAD

**Issue by Gijsbertbas** [trhallam/segysak#35]
I get a `TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'str'` from pandas originating from the segy_loader when running `segysak convert examples/data/volve10r12-full-twt-sub3d.sgy --crop 10090 10100 2150 2160`

**Comment by trhallam** [comment]
see commit https://github.com/trhallam/segysak/commit/4b0b0b500445234cf1ddf5c4600ad529c4826ac7

**Comment by Gijsbertbas** [comment]
fixed thank you!
