### ISSUE TITLE
The Full F3 SEGY does not load

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#4]
using a naive call to 
```
seismic = segy_loader(full_segy_file)
```

in a notebook causes the kernel to die after the header scan 

file is available here: https://s3.us-east-2.amazonaws.com/seismic.euclidity.com/F3/f3_seismic_full.sgy

**Comment by trhallam** [comment]
Managed to fully load the dataset. Might be setup specific.

**Comment by stevejpurves** [comment]
I'll retry this

**Comment by trhallam** [comment]
Did this work for you steve?

**Comment by stevejpurves** [comment]
All fine now,
