### ISSUE TITLE
Extract data along well track

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#49]
It looks like this is a great fit for the exact approach in the xarray docs for advanced interpolation http://xarray.pydata.org/en/stable/interpolation.html#advanced-interpolation

**Comment by trhallam** [comment]
Example added in https://github.com/trhallam/segysak/commit/b5ab8e0aa3dbd5906296039c7746f5ab16ca33b7 to arbitrary_line_extraction
