### ISSUE TITLE
catch bad segyio Enum prior to loading/scanning

### ISSUE THREAD

**Issue by trhallam** [trhallam/segysak#64]
If the Enum is not valid for SEGYIO then it should be caught and an error raised prior to scanning to catch user input errors.

For example, here 194 is a typo and should be 193

```
segy.segy_loader(template, iline=189, xline=194)
```

**Comment by trhallam** [comment]
@stpotter16 thanks for submitting a PR, even though we didn't end up using it.

If you have any others, feel free to submit them.

**Comment by stpotter16** [comment]
No problem! I don't have any at the moment, but I might grab #75 later in my day if you don't get to it.
