### ISSUE TITLE
surface_from_points with 2D data

### ISSUE THREAD

**Issue by adamchengtkc** [trhallam/segysak#70]
Is there a way to adjust the interpolation distance of points to a 2D line?
Say I have 2 parallel 2D lines, in separate survey A & B. I have a horizon interpreted on B. When I load survey A in segysak and use surface_from_points to plot the horizon, segysak will project horizon drawn on B and plotted on A

Nice if we can set the maximum distance to project on points to 2D seismic

Thanks

**Comment by trhallam** [comment]
Hi @adamchengtkc , `surface_from_points` is primarily designed to work when the surface intersects the line. I think what `xarray` is doing here is using the nearest points to the line in the projection. My suggestion would be to use the x and y coordinates to calculate the distance, and then apply this as a mask to your survey A interpretation.

**Comment by adamchengtkc** [comment]
Thanks.will try your suggestion.
