### ISSUE TITLE
conda environment

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#8]
Should we be providing a conda environment file alongside or in place of the requirements.txt?

**Comment by trhallam** [comment]
Should test against the gostin env.

**Comment by stevejpurves** [comment]
@trhallam we can also be quite free and add the requirements from the example notebooks in here the environments too as the setup.py it what looks after the core package requirements, is that right?

**Comment by trhallam** [comment]
Picking this up due to nbsphinx and rtd requirements.

**Comment by trhallam** [comment]
added in https://github.com/trhallam/segysak/commit/a12d5c0e63c7572ca63b5335f52c9a0bf893f3b4
