### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by stevejpurves** [trhallam/segysak#9]
Publish to pypi for linux and windows using Github Actions. Python 3.6+

**Comment by JesperDramsch** [comment]
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by trhallam** [comment]
Setup some basic workflows to test publish on the dev branch.
Added the API keys for PYPI. 

- [ ] need to migrate test workflow to a proper publication workflow at end of week.
